import { Link } from "react-router-dom";
import { ArrowLeft, FileText, Clock } from "lucide-react";
import { Heading1, Heading2, BodyText } from "../components/Typography";
import Footer from "../components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[var(--bg-base)] text-[var(--text-primary)] py-12 px-4 sm:px-6 flex flex-col justify-between items-center">
      <div className="w-full max-w-2xl mb-6">
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-sm text-[var(--text-muted)] hover:text-[var(--accent-primary)] transition-colors focus:outline-none focus:ring-2 focus:ring-[var(--accent-primary)] focus:ring-offset-2 focus:ring-offset-[var(--bg-base)] rounded"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
      </div>

      <div className="w-full max-w-2xl bg-[var(--bg-surface)] backdrop-blur-[24px] border border-[var(--accent-primary)]/12 rounded-2xl p-6 sm:p-8 shadow-2xl my-auto">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-[var(--accent-primary)]/10 flex items-center justify-center text-[var(--accent-primary)]">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <Heading1>Terms of Service</Heading1>
            <div className="flex items-center gap-1.5 text-xs text-[var(--text-muted)] mt-0.5">
              <Clock className="w-3.5 h-3.5" /> Last updated: August 21, 2026
            </div>
          </div>
        </div>

        <div className="space-y-6 text-[var(--text-primary)]/90 text-sm leading-relaxed">
          <section className="space-y-2">
            <Heading2>1. Age Eligibility (18+)</Heading2>
            <BodyText>
              Lyra is an artificial intelligence companion intended exclusively for adults aged 18 and older. By accessing or using the application, you represent and warrant that you meet this age requirement.
            </BodyText>
          </section>

          <section className="space-y-2">
            <Heading2>2. Acceptable Use</Heading2>
            <BodyText>
              You agree not to misuse the service. Prohibited activities include attempting to scrape API endpoints, reverse-engineering or redistributing 3D VRM assets, or using the application for any unlawful purposes.
            </BodyText>
          </section>

          <section className="space-y-2">
            <Heading2>3. Intellectual Property</Heading2>
            <BodyText>
              The application architecture, design tokens, source code, and associated 3D VRM character assets are owned and protected by their respective creators. Unauthorized extraction or commercial replication is strictly prohibited.
            </BodyText>
          </section>

          <section className="space-y-2">
            <Heading2>4. AI Character Disclaimer</Heading2>
            <BodyText>
              Lyra is an artificial intelligence character, not a real person, and not a licensed therapist, medical professional, or counselor. Nothing generated by Lyra constitutes professional psychological or medical advice.
            </BodyText>
            <div className="p-3.5 rounded-xl bg-[var(--accent-primary)]/5 border border-[var(--accent-primary)]/20 text-xs text-[var(--accent-primary)]">
              If you are experiencing a mental health crisis or emotional distress, please reach out immediately to a support hotline or crisis lifeline (e.g., dial 988 in the US/Canada or contact your local emergency services).
            </div>
          </section>

          <section className="space-y-2">
            <Heading2>5. Limitation of Liability</Heading2>
            <BodyText>
              The service is provided on an "as is" and "as available" basis without warranties of any kind. We disclaim all liability for any indirect, incidental, or consequential damages arising from your use of the application.
            </BodyText>
          </section>

          <section className="space-y-2">
            <Heading2>6. Governing Law</Heading2>
            <BodyText>
              These terms shall be governed by and construed in accordance with the laws of the applicable jurisdiction without regard to conflict of law provisions.
            </BodyText>
          </section>
        </div>
      </div>

      <Footer />
    </div>
  );
}
